
# Set Desired Working Directory
#setwd('Documents/PGCBA/Placement/Sagitec/SSN_SACE_2017_Jan-master/CSV')

require(data.table)

# reading data
file_names <- c('prescriber.detailed.csv', 'prescriber.summary.csv',
                'PUF_pres_conso.csv', 'PUF.detailed.csv', 'PUF.summary.csv')
list_1 <- lapply(file_names, fread, stringsAsFactors = T) # easier to search for attribute
str(list_1)

# variables in each data table
dt_names <- lapply(list_1, names)

# get all unique variable names
all_names <- vector()
for (i in 1:length(list_1)) {
  a <- names(list_1[[i]])
  all_names <- unique(c(a, all_names))
}
length(all_names)


# Setting up Data Dictionary
require(gdata)
full_att_desc <- read.xls('Data_Desc.xlsx') # ignore warnings !
length(full_att_desc$Attribute)
require(stringr)
str_count(full_att_desc$Attribute[1]) # needs to be trimmed, since, npi is only 3 characters long
full_att_desc$Attribute <- str_trim(full_att_desc$Attribute)
require(dplyr)
attr_desc <- select(full_att_desc, Attribute,Description) %>% filter(full_att_desc$Attribute %in% all_names)
dim(attr_desc)
length(all_names)
# Redundant Operation !
#missing_attr_desc <- all_names[which(!(all_names %in% attr_desc$Attribute))]
#missing_attr_desc_which_dataSet <- list()
#for (i in 1:length(missing_attr_desc)) {
#  missing_attr_desc_which_dataSet[[i]] <- which(dt_names %like% missing_attr_desc[i])
#}
#names(missing_attr_desc_which_dataSet) <- missing_attr_desc
#missing_attr_desc_which_dataSet

find_desc <- function(att_name, match = 2) {
  require(data.table)
  if (match == 0) {
    if (length(att_name) > 1) {
      stop('\n', 'Have you specified the following;', '\n\t','match = 0 for desc of all attributes with similar name',
           '\n\t', 'match = 1 for desc of attributes in a specific data table', 
           '\n', 'If you are searching for more than 1 attribute, please use lapply(<names_vector>,<function>, <match>)')
    } else if (any(attr_desc$Attribute %like% att_name)) {
      # Useful >> when you wish to look at desc of all attributes with similar name
      attr_desc[which(attr_desc$Attribute %like% att_name),]
    } else {
      warning(att_name,' not found !')
    }
  } else if (match == 1) {
    # Useful >> when you wish to look at desc of attributes in a specific data table
    if (length(att_name) > 1) {
      stop('\n', 'Have you specified the following;', '\n\t','match = 0 for desc of all attributes with similar name',
           '\n\t', 'match = 1 for desc of attributes in a specific data table', 
           '\n', 'If you are searching for more than 1 attribute, please use lapply(<names_vector>,<function>, <match>)')
    } else if (any(attr_desc$Attribute %like% att_name)) {
      attr_desc[match(att_name,attr_desc$Attribute),]
    } else {
      warning(att_name,' not found !')
    }
  } else if (match != 0 & match != 1) {
    stop('\n', 'Have you specified the following;', '\n\t','match = 0 for desc of all attributes with similar name',
         '\n\t', 'match = 1 for desc of attributes in a specific data table', 
         '\n', 'If you are searching for more than 1 attribute, please use lapply(<names_vector>,<function>, <match>)')
  }
}

# Testing
find_desc('generic_name')
find_desc(c('npi', 'drug_name')) # works !!
lapply(c('bene_count_ge65', 'total_claim_count'), find_desc, match = 0)
lapply(dt_names[[5]], find_desc, match = 1)

# need to troubleshoot !!
#find_att_desc <- function(att_name) {
#  att_desc <- list()
#  for (i in 1:length(att_name)) {
#    att_desc[[i]] <- att_desc[which(att_desc$Attribute %like% att_name[i]),]
#  }
#  att_desc
#}
#find_att_desc(att_name = c('bene_count_ge65', 'total_claim_count'))


# split into tables
presc_detail <- list_1[[1]] # 'prescriber.detailed.csv'
presc_sumry <- list_1[[2]] # 'prescriber.summary.csv'
PUF_conso <- list_1[[3]] # 'PUF_pres_conso.csv'
PUF_detail <- list_1[[4]] # 'PUF.detailed.csv'
PUF_sumry <- list_1[[5]] # 'PUF.summary.csv

names(dt_names) <- c('presc_detail', 'presc_sumry', 'PUF_conso', 'PUF_detail', 'PUF_sumry')

# Finding tables corresponding to attribute (pattern)
names(dt_names)[which(dt_names %like% 'total_claim_count')]


lapply(dt_names[[1]], find_desc, match = 1)

# is doc_id similar to npi ? npi must have 10, while doc_id has 2+7. # is doc_id generated by data provider ?
which(dt_names %like% '.*doc_id*')
str_count(presc_detail$doc_id[1])
doc_id_string_counter <- function(x) {
  doc_id_length <- lapply(x$doc_id, str_count)
  less_than <- 0
  greater_than <- 0
  actual <- 0
  for (i in 1:length(x$doc_id)) {
    if (doc_id_length[[i]] < 9) {
      less_than <- less_than + 1
    } else if (doc_id_length[[i]] > 9) {
      greater_than <- greater_than + 1
    } else if (doc_id_length[[i]] == 9) {
      actual <- actual + 1
    }
  }
  if (actual == length(x$doc_id)) {
    paste('Charater length is equal 9 for all doc_id')
  } else {
    c(less_than, greater_than)
  }
}

doc_id_string_counter(presc_detail)
doc_id_string_counter(presc_sumry)
doc_id_string_counter(PUF_conso)
doc_id_string_counter(PUF_detail)
doc_id_string_counter(PUF_sumry)

lapply(dt_names[[1]], find_desc, match = 1)

# state & city in PUF_conso same as provider_* in others ? # need to look into it !
all_names[all_names %like% '.*provider*']
which(dt_names %like% '.*provider*')
head(names(PUF_conso))

# how to handle state = 'ZZ' ? # foreign vs domestic ?
sum(presc_detail$nppes_provider_state == 'ZZ')
state_zz <- presc_detail[presc_detail$nppes_provider_state == 'ZZ']

unique(state_zz$doc_id)

select(presc_detail, doc_id, nppes_provider_state) %>% filter(doc_id == 'SR7876440') # No other state
select(presc_detail, doc_id, nppes_provider_state) %>% filter(doc_id == 'ZH4066278') # No other state
select(presc_detail, doc_id, nppes_provider_state) %>% filter(doc_id == 'PI6937446') # No other state
select(presc_detail, doc_id, nppes_provider_state) %>% filter(doc_id == 'FP6297812') # No other state

select(presc_detail, doc_id, nppes_provider_city) %>% filter(doc_id == 'SR7876440') # No other city
select(presc_detail, doc_id, nppes_provider_city) %>% filter(doc_id == 'ZH4066278') # No other city
select(presc_detail, doc_id, nppes_provider_city) %>% filter(doc_id == 'PI6937446') # No other city
select(presc_detail, doc_id, nppes_provider_city) %>% filter(doc_id == 'FP6297812') # No other city

select(presc_detail, doc_id, nppes_provider_city, nppes_provider_state) %>%
  filter(nppes_provider_city == "JAIPUR") # No other state
select(presc_detail, doc_id, nppes_provider_city, nppes_provider_state) %>%
  filter(nppes_provider_city == "TORONTO") # No other state
select(presc_detail, doc_id, nppes_provider_city, nppes_provider_state) %>%
  filter(nppes_provider_city == "ST. JOHN'S") # No other state
select(presc_detail, doc_id, nppes_provider_city, nppes_provider_state) %>%
  filter(nppes_provider_city == "DARTMOUTH") # No other state

# New Feature
presc_detail$cost_per_day_per_claim <- round(presc_detail$total_drug_cost/presc_detail$total_day_supply/presc_detail$total_claim_count, digits = 3)

# Plotting by drug_name for bene_count based split
drug_generic_bene_NA <- select(presc_detail, doc_id:cost_per_day_per_claim) %>% filter(is.na(bene_count))
drug_generic_bene <- select(presc_detail, doc_id:cost_per_day_per_claim) %>% filter(!is.na(bene_count))
length(unique(drug_generic_bene_NA$drug_name))
length(unique(drug_generic_bene$drug_name))
intersect_bene <- intersect(drug_generic_bene_NA$drug_name, drug_generic_bene$drug_name)

split_drug_generic_bene_NA <- split(drug_generic_bene_NA, as.factor(drug_generic_bene_NA$drug_name))
length(split_drug_generic_bene_NA)
split_drug_generic_bene <- split(drug_generic_bene, as.factor(drug_generic_bene$drug_name))
length(split_drug_generic_bene)

boxplot_drug_bene_NA <- function(drug_name) {
  if (any(names(split_drug_generic_bene_NA) %in% drug_name)) {
    drug_index_NA <- which(names(split_drug_generic_bene_NA) %in% drug_name)
    feature_index_NA <- which(colnames(split_drug_generic_bene_NA[[drug_index_NA]]) %in% 'cost_per_day_per_claim')
    boxplot(split_drug_generic_bene_NA[[drug_index_NA]][[feature_index_NA]], xlab = 'bene_NA', ylab = 'cost/day/claim')
  } else {
    stop('Please enter a valid drug_name.')
  }
}


boxplot_drug_bene <- function(drug_name) {
  if (any(names(split_drug_generic_bene) %in% drug_name)) {
    drug_index <- which(names(split_drug_generic_bene) %in% drug_name)
    feature_index <- which(colnames(split_drug_generic_bene[[drug_index]]) %in% 'cost_per_day_per_claim')
    boxplot(split_drug_generic_bene[[drug_index]][[feature_index]], xlab = 'bene', ylab = 'cost/day/claim')
  } else {
    stop('Please enter a valid drug_name')
  }
}

# The range and outliers for those in bene_NA seem to be greater than the other
# Can we claim that these records could be further scrutinized ? Drill Down to Location ?

boxplot_drug_bene_split <- function(drug_name) {
  if (any(intersect_bene %in% drug_name)) {
    par(mfrow=c(1,2))
    boxplot_drug_bene_NA(drug_name)
    boxplot_drug_bene(drug_name)
    par(mfrow=c(1,1))
  } else {
    stop('Please enter drug_name that has both NA and non-NA values under bene_count')
  }
}

# Testing
#unique(drug_generic_bene$drug_name)[which(!(unique(drug_generic_bene$drug_name) %in% intersect_bene))]
boxplot_drug_bene_split(drug_name = 'ZEMAIRA') # works !!
boxplot_drug_bene_split(drug_name = 'CARBIDOPA-LEVODOPA')

# MultiBrand Drugs
length(unique(presc_detail$generic_name))
require(dplyr)
grouped_unique_generic_name <- select(presc_detail, drug_name, generic_name) %>% split(f = presc_detail$generic_name) %>% lapply(FUN = unique)
length(grouped_unique_generic_name)
x_generic_unique_name <- sapply(grouped_unique_generic_name, nrow)
length(x_generic_unique_name)
multibrand_generic_vector <- x_generic_unique_name[x_generic_unique_name > 1]
length(multibrand_generic_vector)
#Verification
#c('drug_name', 'generic_name') %in% colnames(presc_detail)
#colnames(presc_detail) %in% c('drug_name', 'generic_name')
sum(presc_detail$drug_name %in% names(multibrand_generic_vector))

multibrand_generic_names <- names(x_generic_unique_name)[x_generic_unique_name > 1]
length(multibrand_generic_names)
single_or_generic_drugs <- names(x_generic_unique_name)[x_generic_unique_name == 1]
length(single_or_generic_drugs)

# Unique Generic Names
unique_generic_name <- unique(presc_detail$generic_name)

# Generic Usage Score

score_top_1 <- vector()
for(i in 1:length(PUF_conso$top1_drug_prescribed)) {
  if(PUF_conso$top1_drug_prescribed[i] %in% unique_generic_name) {
    score_top_1[i] <- 1
  } else {
    score_top_1[i] <- 0
  }
}
PUF_conso$score_top_1 <- score_top_1

score_top_2 <- vector()
for(i in 1:length(PUF_conso$top2_drug_prescribed)) {
  if(PUF_conso$top2_drug_prescribed[i] %in% unique_generic_name) {
    score_top_2[i] <- 1
  } else {
    score_top_2[i] <- 0
  }
}
PUF_conso$score_top_2 <- score_top_2

score_top_3 <- vector()
for(i in 1:length(PUF_conso$top3_drug_prescribed)) {
  if(PUF_conso$top3_drug_prescribed[i] %in% unique_generic_name) {
    score_top_3[i] <- 1
  } else {
    score_top_3[i] <- 0
  }
}
PUF_conso$score_top_3 <- score_top_3

score_top_4 <- vector()
for(i in 1:length(PUF_conso$top4_drug_prescribed)) {
  if(PUF_conso$top4_drug_prescribed[i] %in% unique_generic_name) {
    score_top_4[i] <- 1
  } else {
    score_top_4[i] <- 0
  }
}
PUF_conso$score_top_4 <- score_top_4

score_top_5 <- vector()
for(i in 1:length(PUF_conso$top5_drug_prescribed)) {
  if(PUF_conso$top5_drug_prescribed[i] %in% unique_generic_name) {
    score_top_5[i] <- 1
  } else {
    score_top_5[i] <- 0
  }
}
PUF_conso$score_top_5 <- score_top_5

PUF_conso$total_score_top <- score_top_1 + score_top_2 + score_top_3 + score_top_4 + score_top_5

# Most doc_ids prescribe more branded drugs than generic ones
barplot(table(PUF_conso$total_score_top))
use_generic <- PUF_conso %>% select(doc_id,total_score_top) %>%
                group_by(doc_id) %>% summarise(total_score_top = mean(total_score_top))

# Nearly, 51 % of doc_ids don't prescribe generic drugs at all
100 - (mean(use_generic$total_score_top > 0)*100)

# Grouping by Doc_ID
length(unique(presc_detail$doc_id))
grouped_unique_doc_id <- select(presc_detail, doc_id:nppes_provider_state) %>% split(f = presc_detail$doc_id) %>% lapply(FUN = unique)
length(grouped_unique_doc_id)
x_doc_id <- sapply(grouped_unique_doc_id, nrow)
head(x_doc_id)

# doc_ids in presc_detail provide services only in 1 location
length(x_doc_id[x_doc_id >1])

# Doctors: Different Brands for a Drug
grouped_unique_doc_id_generic_name <- select(presc_detail, doc_id, drug_name:generic_name) %>%
  split(f = presc_detail$doc_id) %>%
  lapply(FUN = unique)
head(grouped_unique_doc_id_generic_name, 1)
grouped_unique_doc_id_generic_name[[1]][[3]] # need to drop unused levels
table_grouped_unique_doc_id_generic_name <- lapply(grouped_unique_doc_id_generic_name,
                                                   function(x){
                                                     select(x, generic_name) %>% droplevels() %>% table()
                                                   })
head(table_grouped_unique_doc_id_generic_name, 1)
table_grouped_unique_doc_id_generic_name[[2]] == 1
doc_id_diff_brand_generic <- sapply(table_grouped_unique_doc_id_generic_name,
                                    function(x){
                                      sum(x > 1)
                                    })
head(doc_id_diff_brand_generic)

# 64.3% of the doc_ids don't seem to prescribe the same brand for a drug... they tend to juggle b/w brands for each prescription ?!
(mean(doc_id_diff_brand_generic > 0))*100


# Common doc_ids
jk_1 <- intersect(presc_detail$doc_id, presc_sumry$doc_id)
jk_2 <- intersect(PUF_detail$doc_id, PUF_sumry$doc_id)
jk_3 <- intersect(jk_2, PUF_conso$doc_id)
jk <- intersect(jk_3, jk_1)
head(jk)
length(jk)

#
doc_id_proportion_diff_brand_generic <- sapply(table_grouped_unique_doc_id_generic_name,
                                               function(x){
                                                 (mean(x > 1))
                                               })
summary(doc_id_proportion_diff_brand_generic)

# Function to identify top candidates to target based on cost/day/claim, generic prescription, likelihood to switch
find_top_candidates <- function(generic_drug_name, n = 10) {
  if(!(generic_drug_name %in% unique(presc_detail$generic_name))) {
    stop('Please enter valid generic_name')
  } else {
    x <- which(names(table_grouped_unique_doc_id_generic_name) %in% jk)
    x_1 <- table_grouped_unique_doc_id_generic_name[x]
    x_2 <- lapply(x_1, names)
    require(data.table)
    x_3 <- names(x_2)[which(x_2 %like% generic_drug_name)]
    require(plotrix)
    y_1 <- presc_detail %>%
      select(doc_id,generic_name,cost_per_day_per_claim)  %>%
      filter((presc_detail$doc_id = presc_detail$doc_id %in% x_3) & presc_detail$generic_name == generic_drug_name) %>%
      group_by(doc_id, generic_name) %>% # needed to address condition where the doc_id prescribes diff brands
      summarise(median(cost_per_day_per_claim))
    y_1$cost_score <- rescale(y_1$`median(cost_per_day_per_claim)`, range(1:100))
    y_2 <- y_1[,-3]
    switch_chance <- vector()
    for(i in 1:length(y_2$doc_id)) {
      switch_chance[i] <- doc_id_proportion_diff_brand_generic[names(doc_id_proportion_diff_brand_generic) == y_2$doc_id[i]]
    }
    switch_chance <- rescale(switch_chance, range(1:100))
    y_3 <- cbind(as.data.frame(y_2),switch_chance)
    x_4 <- PUF_conso %>% select(doc_id, total_score_top) %>%
      filter(doc_id %in% x_3) %>% group_by(doc_id) %>%
      summarise(total_score_top = mean(total_score_top))
    generic_usage_score <- vector()
    for(i in 1:length(y_3$doc_id)) {
      generic_usage_score[i] <- x_4$total_score_top[which(as.character(x_4$doc_id) ==  as.character(y_3$doc_id[i]))]
    }
    generic_usage_score <- rescale(generic_usage_score, range(1:100))
    y_4 <- cbind(y_3,generic_usage_score)
    y_4$Final_Score <- (y_4$cost_score + y_4$switch_chance + y_4$generic_usage_score)/3
    y_5 <- y_4[,-2] %>% arrange(desc(Final_Score))
    head(y_5, n)
  }
}

head(unique_generic_name)
find_top_candidates('zadkanso', 5) # works !! :D
find_top_candidates('GABAPENTIN', 5) # works !! :D