
# Set Desired Working Directory
#setwd('Documents/PGCBA/Placement/Sagitec/SSN_SACE_2017_Jan-master/CSV')

require(data.table)

# reading data
file_names <- c('prescriber.detailed.csv', 'prescriber.summary.csv',
                'PUF_pres_conso.csv', 'PUF.detailed.csv', 'PUF.summary.csv')
list_1 <- lapply(file_names, fread) # easier to search for attribute
str(list_1)

# variables in each data table
dt_names <- lapply(list_1, names)

# get all unique variable names
all_names <- vector()
for (i in 1:length(list_1)) {
  a <- names(list_1[[i]])
  all_names <- unique(c(a, all_names))
}
length(all_names)


# Setting up Data Dictionary
require(gdata)
full_att_desc <- read.xls('Data_Desc.xlsx') # ignore warnings !
length(full_att_desc$Attribute)
require(stringr)
str_count(full_att_desc$Attribute[1]) # needs to be trimmed, since, npi is only 3 characters long
full_att_desc$Attribute <- str_trim(full_att_desc$Attribute)
require(dplyr)
attr_desc <- select(full_att_desc, Attribute,Description) %>% filter(full_att_desc$Attribute %in% all_names)
dim(attr_desc)
length(all_names)
# Redundant Operation !
#missing_attr_desc <- all_names[which(!(all_names %in% attr_desc$Attribute))]
#missing_attr_desc_which_dataSet <- list()
#for (i in 1:length(missing_attr_desc)) {
#  missing_attr_desc_which_dataSet[[i]] <- which(dt_names %like% missing_attr_desc[i])
#}
#names(missing_attr_desc_which_dataSet) <- missing_attr_desc
#missing_attr_desc_which_dataSet

find_desc <- function(att_name, match = 2) {
  if (match == 0) {
    if (length(att_name) > 1) {
      stop('To search for more than 1 attribute, use lapply(<names_vector>,<function>)', '\n','Please remember to enter: match = 0 for desc of all attributes with similar name (or) match = 1 for desc of attributes in a specific data table')
    } else if (any(attr_desc$Attribute %like% att_name)) {
      # Useful >> when you wish to look at desc of all attributes with similar name
      attr_desc[which(attr_desc$Attribute %like% att_name),]
    } else {
      warning(att_name,' not found !')
    }
  } else if (match == 1) {
    # Useful >> when you wish to look at desc of attributes in a specific data table
    if (length(att_name) > 1) {
      stop('To search for more than 1 attribute, use lapply(<names_vector>,<function>)', '\n','Please remember to enter: match = 0 for desc of all attributes with similar name (or) match = 1 for desc of attributes in a specific data table')
    } else if (any(attr_desc$Attribute %like% att_name)) {
      attr_desc[match(att_name,attr_desc$Attribute),]
    } else {
      warning(att_name,' not found !')
    }
  } else if (match != 0 & match != 1) {
    stop('To search for more than 1 attribute, use lapply(<names_vector>,<function>)', '\n','Please remember to enter: match = 0 for desc of all attributes with similar name (or) match = 1 for desc of attributes in a specific data table')
  }
}

# Testing
find_desc(c('npi', 'drug_name')) # works !!
lapply(c('bene_count_ge65', 'total_claim_count'), find_desc, match = 0)
lapply(dt_names[[5]], find_desc, match = 1)

# need to troubleshoot !!
#find_att_desc <- function(att_name) {
#  att_desc <- list()
#  for (i in 1:length(att_name)) {
#    att_desc[[i]] <- att_desc[which(att_desc$Attribute %like% att_name[i]),]
#  }
#  att_desc
#}
#find_att_desc(att_name = c('bene_count_ge65', 'total_claim_count'))


# split into tables
dt_1 <- list_1[[1]] # 'prescriber.detailed.csv'
dt_2 <- list_1[[2]] # 'prescriber.summary.csv'
dt_3 <- list_1[[3]] # 'PUF_pres_conso.csv'
dt_4 <- list_1[[4]] # 'PUF.detailed.csv'
dt_5 <- list_1[[5]] # 'PUF.summary.csv

lapply(dt_names[[1]], find_desc, match = 1)

# is doc_id similar to npi ? npi must have 10, while doc_id has 2+7. # is doc_id generated by data provider ?
which(dt_names %like% '.*doc_id*')
str_count(dt_1$doc_id[1])
doc_id_string_counter <- function(x) {
  doc_id_length <- lapply(x$doc_id, str_count)
  less_than <- 0
  greater_than <- 0
  actual <- 0
  for (i in 1:length(x$doc_id)) {
    if (doc_id_length[[i]] < 9) {
      less_than <- less_than + 1
    } else if (doc_id_length[[i]] > 9) {
      greater_than <- greater_than + 1
    } else if (doc_id_length[[i]] == 9) {
      actual <- actual + 1
    }
  }
  if (actual == length(x$doc_id)) {
    paste('Charater length is equal 9 for all doc_id')
  } else {
    c(less_than, greater_than)
  }
}

doc_id_string_counter(dt_1)
doc_id_string_counter(dt_2)
doc_id_string_counter(dt_3)
doc_id_string_counter(dt_4)
doc_id_string_counter(dt_5)

lapply(dt_names[[1]], find_desc, match = 1)

# state & city in dt_3 same as provider_* in others ? # need to look into it !
all_names[all_names %like% '.*provider*']
which(dt_names %like% '.*provider*')
head(names(dt_3))

# how to handle state = 'ZZ' ? # foreign vs domestic ?
sum(dt_1$nppes_provider_state == 'ZZ')
state_zz <- dt_1[dt_1$nppes_provider_state == 'ZZ']

unique(state_zz$doc_id)

select(dt_1, doc_id, nppes_provider_state) %>% filter(doc_id == 'SR7876440') # No other state
select(dt_1, doc_id, nppes_provider_state) %>% filter(doc_id == 'ZH4066278') # No other state
select(dt_1, doc_id, nppes_provider_state) %>% filter(doc_id == 'PI6937446') # No other state
select(dt_1, doc_id, nppes_provider_state) %>% filter(doc_id == 'FP6297812') # No other state

select(dt_1, doc_id, nppes_provider_city) %>% filter(doc_id == 'SR7876440') # No other city
select(dt_1, doc_id, nppes_provider_city) %>% filter(doc_id == 'ZH4066278') # No other city
select(dt_1, doc_id, nppes_provider_city) %>% filter(doc_id == 'PI6937446') # No other city
select(dt_1, doc_id, nppes_provider_city) %>% filter(doc_id == 'FP6297812') # No other city

select(dt_1, doc_id, nppes_provider_city, nppes_provider_state) %>%
  filter(nppes_provider_city == "JAIPUR") # No other state
select(dt_1, doc_id, nppes_provider_city, nppes_provider_state) %>%
  filter(nppes_provider_city == "TORONTO") # No other state
select(dt_1, doc_id, nppes_provider_city, nppes_provider_state) %>%
  filter(nppes_provider_city == "ST. JOHN'S") # No other state
select(dt_1, doc_id, nppes_provider_city, nppes_provider_state) %>%
  filter(nppes_provider_city == "DARTMOUTH") # No other state

# New Feature
dt_1$cost_per_day_per_claim <- round(dt_1$total_drug_cost/dt_1$total_day_supply/dt_1$total_claim_count, digits = 3)

# Plotting by drug_name for bene_count based split
drug_generic_bene_NA <- select(dt_1, doc_id:cost_per_day_per_claim) %>% filter(is.na(bene_count))
drug_generic_bene <- select(dt_1, doc_id:cost_per_day_per_claim) %>% filter(!is.na(bene_count))
length(unique(drug_generic_bene_NA$drug_name))
length(unique(drug_generic_bene$drug_name))
intersect_bene <- intersect(drug_generic_bene_NA$drug_name, drug_generic_bene$drug_name)

split_drug_generic_bene_NA <- split(drug_generic_bene_NA, as.factor(drug_generic_bene_NA$drug_name))
length(split_drug_generic_bene_NA)
split_drug_generic_bene <- split(drug_generic_bene, as.factor(drug_generic_bene$drug_name))
length(split_drug_generic_bene)

boxplot_drug_bene_NA <- function(drug_name) {
  if (any(names(split_drug_generic_bene_NA) %in% drug_name)) {
    drug_index_NA <- which(names(split_drug_generic_bene_NA) %in% drug_name)
    feature_index_NA <- which(colnames(split_drug_generic_bene_NA[[drug_index_NA]]) %in% 'cost_per_day_per_claim')
    boxplot(split_drug_generic_bene_NA[[drug_index_NA]][[feature_index_NA]], xlab = 'bene_NA', ylab = 'cost/day/claim')
  } else {
    stop('Please enter a valid drug_name.')
  }
}


boxplot_drug_bene <- function(drug_name) {
  if (any(names(split_drug_generic_bene) %in% drug_name)) {
    drug_index <- which(names(split_drug_generic_bene) %in% drug_name)
    feature_index <- which(colnames(split_drug_generic_bene[[drug_index]]) %in% 'cost_per_day_per_claim')
    boxplot(split_drug_generic_bene[[drug_index]][[feature_index]], xlab = 'bene', ylab = 'cost/day/claim')
  } else {
    stop('Please enter a valid drug_name')
  }
}

# The range and outliers for those in bene_NA seem to be greater than the other
# Can we claim that these records could be further scrutinized ? Drill Down to Location ?

boxplot_drug_bene_split <- function(drug_name) {
  if (any(intersect_bene %in% drug_name)) {
    par(mfrow=c(1,2))
    boxplot_drug_bene_NA(drug_name)
    boxplot_drug_bene(drug_name)
    par(mfrow=c(1,1))
  } else {
    stop('Please enter drug_name that has both NA and non-NA values under bene_count')
  }
}

# Testing
#unique(drug_generic_bene$drug_name)[which(!(unique(drug_generic_bene$drug_name) %in% intersect_bene))]
boxplot_drug_bene_split(drug_name = 'ZEMAIRA') # works !!
boxplot_drug_bene_split(drug_name = 'CARBIDOPA-LEVODOPA')
